<a href="https://colab.research.google.com/github/prithivi96/AAIC_Python-Assign/blob/main/1_Python_Assignment_v2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
 
 
# you can free to change all these codes/structure
# here A and B are list of lists
def matrix_mul(A, B):
    # write your code
    if len(A[0])==len(B):
      c=0
      e,d = [],[]
      # print(len(B[0]))
      for i in range(len(A[0])):
        # print(i)
        for k in range(len(B[0])):
          for j in range(len(B)):
            c += A[i][j]*B[j][k]
          d.append(c)
          c=0
        e.append(d)
        d=[]
      return e
    else:
      print("Matrix Multiplication is not possible")

A = [[1,3,4],[2,5,7],[5,9,6]]
B = [[1,0,0],[0,1,0],[0,0,1]] 
print(matrix_mul(A, B))

[[1, 3, 4], [2, 5, 7], [5, 9, 6]]


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [ ]:
from random import uniform
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    # your code here for picking an element from with the probability propotional to its magnitude
    c_sum=[]
    sum=0
    for i in range(len(A)):
      sum+=A[i]
      c_sum.append(sum)
    # print(c_sum)
    
    r = int(uniform(0,sum))
    number = 0
    # print(r)
    for index in range(len(A)):
      if r >= c_sum[index] and r <c_sum[index+1]:
        # print(r,c_sum[index],c_sum[index+1],A[index+1])
        return A[index+1]
    return number

def sampling_based_on_magnitued():
    A = [0,5,27,6,13,28,100,45,10,79]
    a = dict()
    for i in range(1,100):
        rnumber = pick_a_number_from_list(A)
        # print(number)
        if rnumber not in a:
          a[rnumber] = 1
        else:
          a[rnumber] +=1
    print(a)

sampling_based_on_magnitued()

{27: 8, 100: 32, 28: 12, 79: 23, 45: 15, 6: 1, 10: 1, 13: 5, 5: 2}


In [ ]:
#Probablitiy of picking a number in a list 

import random 


a =[1,82,4,2]



{11: 5, 3: 5, 7: 9, 4: 12, 8: 14, 2: 7, 5: 8, 9: 9, 6: 7, 10: 5, 0: 13, 1: 6} 
 {35: 3, 0: 1, 12: 4, 61: 1, 54: 3, 18: 2, 27: 2, 37: 4, 49: 4, 25: 1, 47: 3, 22: 2, 32: 1, 5: 1, 11: 2, 48: 3, 63: 1, 41: 5, 44: 2, 64: 1, 4: 2, 34: 2, 23: 2, 56: 1, 60: 6, 42: 3, 14: 2, 2: 1, 36: 3, 40: 5, 50: 1, 58: 4, 62: 1, 46: 3, 9: 2, 8: 1, 39: 1, 1: 1, 24: 1, 33: 2, 43: 1, 13: 1, 20: 1, 21: 1, 29: 1, 3: 1, 57: 1, 59: 1, 6: 1, 16: 1}


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [ ]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):
    # write your code
    y=re.sub('[aA-zZ]','',String)
    z=re.sub('[#,$,%,@,!,^,*]','',y)
    x=re.sub('[0-9]','#',z)
    return(x) # modified string which is after replacing the # with digits

String='#2a$#b%c%561*#'

replace_digits(String)

'####'

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
def display_dash_board(students, marks):
    # write code for computing top top 5 students
    maxmarks = sorted(marks,reverse=True)
    top_5_students = list(students[marks.index(i)] for i in maxmarks[:5] if i in marks)
    # write code for computing top least 5 students
    minmarks=sorted(marks)
    least_5_students = list(students[marks.index(i)] for i in minmarks[:5] if i in marks)
    # write code for computing top least 5 student
    diff=max(marks)-min(marks)
    students_within_25_and_75 = list(students[marks.index(i)] for i in minmarks if i>(diff*0.25) and i<(diff*0.75))
    return top_5_students, least_5_students, students_within_25_and_75

students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(students, marks)
print(top_5_students, least_5_students, students_within_25_and_75)

['student8', 'student10', 'student2', 'student5', 'student7'] ['student3', 'student4', 'student9', 'student6', 'student1'] ['student9', 'student6', 'student1', 'student7', 'student5']


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [ ]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    # write your code here
    distance = []
    for s in S:
        d = math.acos(((s[0]*P[0])+s[1]*P[1])/((math.sqrt(s[0]**2+s[1]**2)*(P[0]**2+P[1]**2))))
        distance.append(d)
    closedistance = sorted(distance)
    closest_points_to_p = list(S[distance.index(i)] for i in closedistance[:5] if i in distance)
    
    return closest_points_to_p  # its list of tuples

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)
print(points) #print the returned values

[(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1)]



<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [ ]:
import math
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
    # your code
    r=0
    b=0
    Rsd1,Bsd1 = [],[]
    intercpt=re.split("[x,y]",line)
    i =list(float(i) for i in intercpt)
    for j in red:
      r=(i[0]*j[0])+(i[1]*j[1])
      if r<=i[2]:
        Rsd1.append(1)
      elif r>i[2]:
        Rsd1.append(0)
    for k in blue:
      b=(i[0]*k[0])+(i[1]*k[1])
      if b<=i[2]:
        Bsd1.append(1)
      elif b>i[2]:
        Bsd1.append(0)
    if (all(Bsd1) and all([not(i) for i in Rsd1])) or (all(Rsd1) and all([not(i) for i in Bsd1])) :
      return "YES"
    else:
      return "NO"
    Bsd1=[]
    Rsd1=[]
    
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    # print(i)
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) # the returned value

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def curve_smoothing(string):
    # your code
    s=string.split(',')
    ct=0
    lftinx=0
    #Replacing left _
    for i in range(len(s)):
        if s[i]=='_':
            ct+=1
        else:
          for k in range(i+1):
            # print(float(s[i])/(ct+1),i,ct,s[k])
            s[k]=(float(s[i])/(ct+1))
            lftinx=i
            leftvalue=float(s[i])
          break
    flag=0
    d=1
    f=0
    #Replacing middle _
    for i in range(lftinx+1,len(s)):
        if s[i]!='_':
            d=(i+1-lftinx)
            flag=i 
            f=float(s[flag])
            break
    for i in range(lftinx,flag+1):
        s[i]=((leftvalue+f)/d)

    #Replacing last _
    lastvalue = float(s[flag])
    for i in range(flag,len(s)):
      if '_' in s:
        s[i]=(lastvalue/(len(s)-flag))

    return s


S=  ["_,_,_,24","40,_,_,_,60","80,_,_,_,_","_,_,30,_,_,_,50,_,_"]
for s in S:
  smoothed_values= curve_smoothing(s)
  print(f"{s} : {smoothed_values}")

_,_,_,24 : [6.0, 6.0, 6.0, 6.0]
40,_,_,_,60 : [20.0, 20.0, 20.0, 20.0, 20.0]
80,_,_,_,_ : [16.0, 16.0, 16.0, 16.0, 16.0]
_,_,30,_,_,_,50,_,_ : [10.0, 10.0, 12.0, 12.0, 12.0, 12.0, 4.0, 4.0, 4.0]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings



# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
    # your code
    # print the output as per the instructions
    cnt_j=0
    allval=[]
    for i in A:
        for j in i:
            allval.append(j)
    for i in A:
        print(f"P(F=={i[0]}|S=={i[1]})={(A.count(i))}/{allval.count(i[1])}")
    
A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

P(F==F1|S==S1)=1/4
P(F==F2|S==S2)=1/3
P(F==F3|S==S3)=1/3
P(F==F1|S==S2)=1/3
P(F==F2|S==S3)=1/3
P(F==F3|S==S2)=1/3
P(F==F2|S==S1)=1/4
P(F==F4|S==S1)=1/4
P(F==F4|S==S3)=1/3
P(F==F5|S==S1)=1/4


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    # your code
    s1=S1.split()
    s2=S2.split()
    a = 0
    b=[]
    c=[]
    for i in s1:
        if i in s2:
            a+=1
        if i not in s2:
            b.append(i)
    for j in s2:
        if j not in s1:
            c.append(j)
    return a,b,c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c=string_features(S1, S2)
print(a,'\n',b,'\n',c)

7 
 ['first', 'F', '5'] 
 ['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
import math

# you can free to change all these codes/structure
def compute_log_loss(A):
    # your code
    log_sum=0
    for i in A:
        log_sum+=((i[0]*math.log(i[1],10))+((1-i[0])*math.log((1-i[1]),10)))
    
    loss = (-1/len(A))*log_sum
    
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(round(loss,7))

0.4243099


In [1]:
!git init


Initialized empty Git repository in /content/.git/


In [3]:
!git add .



In [5]:
!git status


On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)

	new file:   .config/.last_opt_in_prompt.yaml
	new file:   .config/.last_survey_prompt.yaml
	new file:   .config/.last_update_check.json
	new file:   .config/active_config
	new file:   .config/config_sentinel
	new file:   .config/configurations/config_default
	new file:   .config/gce
	new file:   .config/logs/2021.07.16/13.19.23.269640.log
	new file:   .config/logs/2021.07.16/13.19.42.311157.log
	new file:   .config/logs/2021.07.16/13.19.58.237112.log
	new file:   .config/logs/2021.07.16/13.20.04.172291.log
	new file:   .config/logs/2021.07.16/13.20.21.584309.log
	new file:   .config/logs/2021.07.16/13.20.22.328313.log
	new file:   sample_data/README.md
	new file:   sample_data/anscombe.json
	new file:   sample_data/california_housing_test.csv
	new file:   sample_data/california_housing_train.csv
	new file:   sample_data/mnist_test.csv
	new file:   sample_data/mnist_train_small.cs

In [6]:
!git commit -a -m 'Python Assignment'


*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@190f9f17fb6e.(none)')


In [24]:
!git config --global user.email "prithivirajchauhan96@gmail.com"
!git config --global user.name "Prithivi Raj"

In [25]:
!git commit -a -m "Python Assignment"

On branch master
nothing to commit, working tree clean


In [34]:
!git remote add origin "https://github.com/prithivi96/demo-repo.git"

fatal: remote origin already exists.


In [35]:
!git branch

* master


In [36]:
!git push --set-upstream origin master

fatal: could not read Username for 'https://github.com': No such device or address


In [37]:
!git status


On branch master
nothing to commit, working tree clean


In [38]:
!git log

commit 2780c0c4a4471a4caef42910fe96e72f45c95a64 (HEAD -> master)
Author: Prithivi Raj <prithivi03041996@gmail.com>
Date:   Sat Jul 24 05:48:46 2021 +0000

    Python Assignment
